{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import simpy\n",
    "import numpy as np\n",
    "import scipy.stats as st\n",
    "import pandas as pd\n",
    "import copy\n",
    "\n",
    "from simulation import Person,simulate"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Preguntas\n",
    "- Cual es la media de la cantidad de tareas resultas siguiendo cada estrategia?\n",
    "\n",
    "- Comparar que estrategia de administración de tiempo es mas productiva?\n",
    "  - 24-6\n",
    "  - 12-3\n",
    "  - Free\n",
    "\n",
    "- ¿Cuál es la distribución de la cantidad de tareas completadas en la ventana de tiempo de 480 minutos? Esto te permitiría entender cuánto varía el rendimiento de la persona.\n",
    "\n",
    "- ¿Cómo afecta la duración de los descansos a la cantidad de tareas completadas? Podrías comparar las simulaciones con diferentes duraciones de descanso para ver si hay alguna diferencia significativa.\n",
    "\n",
    "- ¿Cómo afectan las interrupciones a la cantidad de tareas completadas? Similar a la pregunta anterior, podrías comparar las simulaciones con y sin interrupciones.\n",
    "\n",
    "- ¿Cuál es la distribución del tiempo entre tareas completadas? Esto te permitiría entender cómo se distribuye el tiempo de trabajo de la persona.\n",
    "\n",
    "- ¿Cómo se correlacionan el número de descansos y el número de tareas completadas? Esto podría ayudarte a entender si tomar más descansos lleva a completar más tareas."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [],
   "source": [
    "import copy\n",
    "\n",
    "def get_prob(n, time, b_time=0, b_duration=0, interruptions=True):\n",
    "    prob = pd.DataFrame({})\n",
    "    \n",
    "    for i in range(n):\n",
    "        env = simpy.Environment()\n",
    "        person = Person(env,'S', b_time, b_duration,interr= interruptions)\n",
    "        env.run(until=time)\n",
    "        env.event().succeed()\n",
    "        env.event().succeed()\n",
    "        env.event().succeed()\n",
    "        \n",
    "        # Data Collecting\n",
    "        prob_row = pd.DataFrame({\n",
    "            \"work_to_work\": [copy.copy(person.work_to_work)],\n",
    "            \"work_to_break\": [copy.copy(person.work_to_break)],\n",
    "            \"work_to_interrupt\": [copy.copy(person.work_to_interrupt)],\n",
    "            \n",
    "            \"break_to_work\": [copy.copy(person.break_to_work)],\n",
    "            \"break_to_interrupt\": [copy.copy(person.break_to_interrupt)],\n",
    "            \n",
    "            \"interrupt_to_work\": [copy.copy(person.interrupt_to_work)],\n",
    "            \"interrupt_to_break\": [copy.copy(person.interrupt_to_break)]\n",
    "        })\n",
    "        \n",
    "        \n",
    "        prob = pd.concat([prob,prob_row])\n",
    "\n",
    "    aux = prob.apply(sum, axis=0)\n",
    "    print(aux.keys())\n",
    "    work_to_break = aux[\"work_to_break\"]\n",
    "    work_to_interrupt = aux[\"work_to_interrupt\"]\n",
    "    \n",
    "    twork =  work_to_break + work_to_interrupt\n",
    "    \n",
    "    break_to_work = aux[\"break_to_work\"]\n",
    "    break_to_interrupt = aux[\"break_to_interrupt\"]\n",
    "    \n",
    "    tbreak = break_to_work + break_to_interrupt\n",
    "    \n",
    "    interrupt_to_work = aux[\"interrupt_to_work\"]\n",
    "    interrupt_to_break = aux[\"interrupt_to_break\"]\n",
    "    \n",
    "    tinterrupt = interrupt_to_break + interrupt_to_work\n",
    "    \n",
    "    print('trabajando -> descansando',work_to_break/twork)\n",
    "    print('trabajando -> interrupcion',work_to_interrupt/twork) \n",
    "    print()\n",
    "    \n",
    "    print('descanso -> interrupcion', break_to_interrupt/tbreak)\n",
    "    print('descansando -> trabajando', break_to_work/tbreak)\n",
    "    print()\n",
    "    \n",
    "    print('interrumpido -> descansando', interrupt_to_break/tinterrupt)\n",
    "    print('interrumpido -> trabajando', interrupt_to_work/tinterrupt)\n",
    "    \n",
    "    \n",
    "    \n",
    "    return prob\n",
    "   \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B9C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 538, in broadcast_arrays\n",
      "    args = [np.array(_m, copy=False, subok=subok) for _m in args]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8CE00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8E0C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8E700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 538, in broadcast_arrays\n",
      "    args = [np.array(_m, copy=False, subok=subok) for _m in args]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189A80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 538, in broadcast_arrays\n",
      "    args = [np.array(_m, copy=False, subok=subok) for _m in args]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8FD80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B240>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9188A40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B4C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9188F40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 538, in broadcast_arrays\n",
      "    args = [np.array(_m, copy=False, subok=subok) for _m in args]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189D00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 538, in broadcast_arrays\n",
      "    args = [np.array(_m, copy=False, subok=subok) for _m in args]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CCB80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 538, in broadcast_arrays\n",
      "    args = [np.array(_m, copy=False, subok=subok) for _m in args]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CC540>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CE340>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9049BC0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CE700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 584, in <genexpr>\n",
      "    all(type(ju.block) is type(first) for ju in join_units)\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CC2C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8E700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8DA80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8C2C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8F9C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8C400>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CF380>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CCB80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 351, in __init__\n",
      "    def __init__(self, block: Block) -> None:\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8E0C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CC180>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8CE00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8FD80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CD940>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B380>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189F80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8D6C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8F4C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918BB00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91882C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904BB00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B740>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189D00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B9C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918AD40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9188A40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189F80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8CE00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 351, in __init__\n",
      "    def __init__(self, block: Block) -> None:\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189300>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\base.py\", line 84, in <genexpr>\n",
      "    return tuple(len(ax) for ax in self.axes)\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918A980>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8C2C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8E700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B4C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\generic.py\", line 42, in _instancecheck\n",
      "    @classmethod  # type: ignore[misc]\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B240>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8FD80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189940>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904A700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CD940>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CC2C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189A80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8E0C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CED40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E4180>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E4540>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CF9C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CD940>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CF380>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8CE00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8F100>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8E700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8C2C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CCB80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B380>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189940>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189F80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CF240>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8FD80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8C400>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B4C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B240>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8DA80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904A700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904BB00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B740>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918A980>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CC2C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189D00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CC180>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E4900>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CE700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\base.py\", line 84, in <genexpr>\n",
      "    return tuple(len(ax) for ax in self.axes)\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E4E00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E5800>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918BD80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189300>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E5300>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918A840>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E5940>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E5BC0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E5A80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E5440>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9188A40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B9C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B740>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B880>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B240>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918AD40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\simpy\\exceptions.py\", line 26, in __init__\n",
      "    def __init__(self, cause: Optional[Any]):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918BD80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\simpy\\exceptions.py\", line 26, in __init__\n",
      "    def __init__(self, cause: Optional[Any]):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189940>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CCB80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B4C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8DA80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8FD80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CF9C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2177, in _grouping_func\n",
      "    def _grouping_func(tup: tuple[int, ArrayLike]) -> tuple[int, DtypeObj]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189D00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\simpy\\events.py\", line 387, in _resume\n",
      "    def _resume(self, event: Event) -> None:\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904A700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\simpy\\events.py\", line 387, in _resume\n",
      "    def _resume(self, event: Event) -> None:\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E5E40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\simpy\\events.py\", line 387, in _resume\n",
      "    def _resume(self, event: Event) -> None:\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904BB00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E4400>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CE700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CD940>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8E700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CC180>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8C2C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8F9C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CCB80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8FD80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\simpy\\core.py\", line 164, in schedule\n",
      "    def schedule(\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904BB00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2191, in _form_blocks\n",
      "    tuples = list(enumerate(arrays))\n",
      "                  ^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8DA80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904A700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8CE00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8F8C400>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CF240>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 538, in broadcast_arrays\n",
      "    args = [np.array(_m, copy=False, subok=subok) for _m in args]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CF380>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 538, in broadcast_arrays\n",
      "    args = [np.array(_m, copy=False, subok=subok) for _m in args]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B740>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 538, in broadcast_arrays\n",
      "    args = [np.array(_m, copy=False, subok=subok) for _m in args]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189300>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 538, in broadcast_arrays\n",
      "    args = [np.array(_m, copy=False, subok=subok) for _m in args]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9188A40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 538, in broadcast_arrays\n",
      "    args = [np.array(_m, copy=False, subok=subok) for _m in args]\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B380>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2177, in _grouping_func\n",
      "    def _grouping_func(tup: tuple[int, ArrayLike]) -> tuple[int, DtypeObj]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9189940>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2177, in _grouping_func\n",
      "    def _grouping_func(tup: tuple[int, ArrayLike]) -> tuple[int, DtypeObj]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E5F80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2177, in _grouping_func\n",
      "    def _grouping_func(tup: tuple[int, ArrayLike]) -> tuple[int, DtypeObj]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CC2C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\simpy\\events.py\", line 332, in __init__\n",
      "    def __init__(self, env: Environment, generator: ProcessGenerator):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E4400>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\simpy\\events.py\", line 332, in __init__\n",
      "    def __init__(self, env: Environment, generator: ProcessGenerator):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E47C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\base.py\", line 84, in <genexpr>\n",
      "    return tuple(len(ax) for ax in self.axes)\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E5580>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\base.py\", line 84, in <genexpr>\n",
      "    return tuple(len(ax) for ax in self.axes)\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A91E4F40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A918B880>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\base.py\", line 84, in <genexpr>\n",
      "    return tuple(len(ax) for ax in self.axes)\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['work_to_work', 'work_to_break', 'work_to_interrupt', 'break_to_work',\n",
      "       'break_to_interrupt', 'interrupt_to_work', 'interrupt_to_break'],\n",
      "      dtype='object')\n",
      "trabajando -> descansando 0.27528568991983626\n",
      "trabajando -> interrupcion 0.7247143100801637\n",
      "\n",
      "descanso -> interrupcion 0.375283384019906\n",
      "descansando -> trabajando 0.624716615980094\n",
      "\n",
      "interrumpido -> descansando 0.185792499315631\n",
      "interrumpido -> trabajando 0.814207500684369\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>work_to_work</th>\n",
       "      <th>work_to_break</th>\n",
       "      <th>work_to_interrupt</th>\n",
       "      <th>break_to_work</th>\n",
       "      <th>break_to_interrupt</th>\n",
       "      <th>interrupt_to_work</th>\n",
       "      <th>interrupt_to_break</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>7</td>\n",
       "      <td>7</td>\n",
       "      <td>29</td>\n",
       "      <td>7</td>\n",
       "      <td>9</td>\n",
       "      <td>29</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>11</td>\n",
       "      <td>16</td>\n",
       "      <td>28</td>\n",
       "      <td>16</td>\n",
       "      <td>9</td>\n",
       "      <td>28</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>6</td>\n",
       "      <td>11</td>\n",
       "      <td>36</td>\n",
       "      <td>11</td>\n",
       "      <td>6</td>\n",
       "      <td>36</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>11</td>\n",
       "      <td>12</td>\n",
       "      <td>33</td>\n",
       "      <td>12</td>\n",
       "      <td>5</td>\n",
       "      <td>33</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>10</td>\n",
       "      <td>13</td>\n",
       "      <td>29</td>\n",
       "      <td>13</td>\n",
       "      <td>10</td>\n",
       "      <td>29</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>10</td>\n",
       "      <td>5</td>\n",
       "      <td>30</td>\n",
       "      <td>5</td>\n",
       "      <td>11</td>\n",
       "      <td>30</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>12</td>\n",
       "      <td>10</td>\n",
       "      <td>33</td>\n",
       "      <td>10</td>\n",
       "      <td>11</td>\n",
       "      <td>33</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>15</td>\n",
       "      <td>11</td>\n",
       "      <td>31</td>\n",
       "      <td>11</td>\n",
       "      <td>2</td>\n",
       "      <td>31</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>6</td>\n",
       "      <td>12</td>\n",
       "      <td>38</td>\n",
       "      <td>12</td>\n",
       "      <td>3</td>\n",
       "      <td>38</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>8</td>\n",
       "      <td>10</td>\n",
       "      <td>32</td>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "      <td>32</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1000 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "    work_to_work  work_to_break  work_to_interrupt  break_to_work  \\\n",
       "0              7              7                 29              7   \n",
       "0             11             16                 28             16   \n",
       "0              6             11                 36             11   \n",
       "0             11             12                 33             12   \n",
       "0             10             13                 29             13   \n",
       "..           ...            ...                ...            ...   \n",
       "0             10              5                 30              5   \n",
       "0             12             10                 33             10   \n",
       "0             15             11                 31             11   \n",
       "0              6             12                 38             12   \n",
       "0              8             10                 32             10   \n",
       "\n",
       "    break_to_interrupt  interrupt_to_work  interrupt_to_break  \n",
       "0                    9                 29                   9  \n",
       "0                    9                 28                   9  \n",
       "0                    6                 36                   6  \n",
       "0                    5                 33                   5  \n",
       "0                   10                 29                  10  \n",
       "..                 ...                ...                 ...  \n",
       "0                   11                 30                  11  \n",
       "0                   11                 33                  11  \n",
       "0                    2                 31                   2  \n",
       "0                    3                 38                   3  \n",
       "0                    3                 32                   3  \n",
       "\n",
       "[1000 rows x 7 columns]"
      ]
     },
     "execution_count": 62,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "get_prob(1000,480)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Estados a lo largo de la simulación: ['I', 'W', 'D', 'W', 'D', 'W', 'I', 'W', 'I', 'W', 'I', 'D', 'I', 'D', 'W', 'I', 'W', 'I', 'W', 'D', 'W', 'I', 'W', 'D', 'I', 'D', 'W', 'I', 'W', 'D', 'I', 'W', 'I', 'W', 'D', 'W', 'I', 'W', 'I', 'D', 'I', 'D', 'W', 'I', 'D', 'W', 'I', 'W', 'D', 'I', 'W', 'I', 'W', 'D', 'I', 'W', 'I', 'D', 'I', 'D', 'I', 'D', 'I', 'W', 'I', 'W', 'I', 'W', 'I', 'W', 'I', 'D', 'W', 'D', 'W', 'I', 'D', 'I', 'W', 'I', 'D', 'I', 'W', 'D', 'W', 'D', 'W', 'I', 'W', 'I', 'W', 'I', 'W', 'I', 'W', 'I', 'W', 'D', 'W', 'I']\n",
      "39 24 38\n",
      "0.38613861386138615 0.2376237623762376 0.37623762376237624\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "\n",
    "# Definición de las probabilidades de transición basadas en los datos proporcionados\n",
    "P = np.array([\n",
    "    [0, 0.27528568991983626, 0.7247143100801637],\n",
    "    [0.624716615980094, 0, 0.375283384019906],\n",
    "    [0.814207500684369, 0.185792499315631, 0]\n",
    "])\n",
    "\n",
    "#variables contadoras\n",
    "interruptions = 0\n",
    "completed_tasks = 1\n",
    "breaks = 0\n",
    "\n",
    "# Estado inicial del trabajador\n",
    "state = 'W'\n",
    "\n",
    "# Número de pasos de tiempo para la simulación\n",
    "Num = 100\n",
    "\n",
    "# Lista para almacenar los estados a lo largo de la simulación\n",
    "simulation = []\n",
    "\n",
    "for _ in range(Num):\n",
    "    if state == 'W':\n",
    "        r = np.random.rand()\n",
    "        if r < P[0, 0]:\n",
    "            state = 'W'\n",
    "        elif r < P[0, 0] + P[0, 1]:\n",
    "            state = 'D'\n",
    "        else:\n",
    "            state = 'I'\n",
    "    elif state == 'D':\n",
    "        r = np.random.rand()\n",
    "        if r < P[1, 0]:\n",
    "            state = 'W'\n",
    "        else:\n",
    "            state = 'I'\n",
    "    else:  # Estado I\n",
    "        r = np.random.rand()\n",
    "        if r < P[2, 0]:\n",
    "            state = 'W'\n",
    "        else:\n",
    "            state = 'D'\n",
    "\n",
    "    if state == 'W':\n",
    "        completed_tasks += 1\n",
    "    elif state == 'D':\n",
    "        breaks += 1\n",
    "    else:\n",
    "        interruptions += 1\n",
    "         \n",
    "\n",
    "        \n",
    "    simulation.append(state)\n",
    "\n",
    "# Imprimir los resultados de la simulación\n",
    "print(\"Estados a lo largo de la simulación:\", simulation)\n",
    "print(completed_tasks, breaks, interruptions)\n",
    "total = completed_tasks + breaks + interruptions\n",
    "print(completed_tasks/total, breaks/total, interruptions/total)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "import copy\n",
    "random.seed(RANDOM_SEED)\n",
    "\n",
    "def simulate(n, time, b_time=0, b_duration=0, interruptions=True, verbose=False, likelihood=False, MSE=[5,5,10,10,30,30,30,30]):\n",
    "    df = pd.DataFrame({})\n",
    "    \n",
    "    i=0\n",
    "    invalid = likelihood\n",
    "    while invalid or i < n:\n",
    "        env = simpy.Environment()\n",
    "        person = Person(env,'S', b_time, b_duration,interr= interruptions)\n",
    "        env.run(until=time)\n",
    "        env.event().succeed()\n",
    "        env.event().succeed()\n",
    "        env.event().succeed()\n",
    "        # Data Collecting\n",
    "        \n",
    "        row = pd.DataFrame(\n",
    "            {  \n",
    "                \"break_duration\": [b_duration], \n",
    "                \"break_timestamp\": [b_time],\n",
    "                \"interruptions\": [copy.copy(person.interrupts)],\n",
    "                \"completed_tasks\": [copy.copy(person.completed_tasks)],\n",
    "                \"breaks\": [copy.copy(person.breaks)],\n",
    "                \"working_time\": [copy.copy(person.task_duration_sum)],\n",
    "                \"break_time\": [copy.copy(person.break_duration_sum)],\n",
    "                \"interruption_time\": [copy.copy(person.interruption_duration_sum)],\n",
    "            }\n",
    "        )\n",
    "        \n",
    "        \n",
    "        df = pd.concat([df,row])\n",
    "        \n",
    "        # To verify stopping criteria\n",
    "        if likelihood:\n",
    "            est_std = df.std()\n",
    "            # print(len(est_std[est_std/np.sqrt(i+1) < MSE]))\n",
    "            invalid = len(est_std[est_std/np.sqrt(i+1) < MSE]) < 8\n",
    "        \n",
    "\n",
    "        # If the simulation verbosity is true the print the outcomes\n",
    "        if verbose:\n",
    "            print(\"Descanso: \",person.breaks)\n",
    "            print(\"Tareas Completadas: \",person.completed_tasks)\n",
    "            print(\"Duración Media de tareas: \",person.task_duration_sum/person.completed_tasks)\n",
    "            print(\"Interrupciónes: \",person.interrupts)\n",
    "\n",
    "        i+=1\n",
    "    \n",
    "    return df\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Extracting Data\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <generator object Person.working at 0x000001C9A896E200>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\generic.py\", line 6320, in __setattr__\n",
      "    object.__setattr__(self, name, value)\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D24F40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\generic.py\", line 6320, in __setattr__\n",
      "    object.__setattr__(self, name, value)\n",
      "RuntimeError: generator ignored GeneratorExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CD940>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\generic.py\", line 6320, in __setattr__\n",
      "    object.__setattr__(self, name, value)\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D25F80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D27EC0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A896D800>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A896D080>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A881C2C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CC540>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904B100>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9049D00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D27100>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8C7B880>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CED40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904AD40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D24CC0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D27380>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CE700>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CCCC0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CCE00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CFB00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90CF100>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\blocks.py\", line 2674, in get_block_type\n",
      "    def get_block_type(dtype: DtypeObj) -> type[Block]:\n",
      "    \n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A881C2C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\generic.py\", line 42, in _instancecheck\n",
      "    @classmethod  # type: ignore[misc]\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A896D080>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\generic.py\", line 42, in _instancecheck\n",
      "    @classmethod  # type: ignore[misc]\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A6265A80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\generic.py\", line 42, in _instancecheck\n",
      "    @classmethod  # type: ignore[misc]\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D27EC0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\generic.py\", line 42, in _instancecheck\n",
      "    @classmethod  # type: ignore[misc]\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D25F80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\generic.py\", line 42, in _instancecheck\n",
      "    @classmethod  # type: ignore[misc]\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D24F40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\generic.py\", line 42, in _instancecheck\n",
      "    @classmethod  # type: ignore[misc]\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A896E200>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A896D800>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D27B00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D24180>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D24540>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D26FC0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D24B80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D274C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\concat.py\", line 310, in _get_combined_plan\n",
      "    for k, mgr in enumerate(mgrs):\n",
      "                  ^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D26AC0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D27880>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D26840>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D27C40>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A8D25580>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904A980>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904AAC0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9049940>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904AFC0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\lib\\stride_tricks.py\", line 542, in <genexpr>\n",
      "    if all(array.shape == shape for array in args):\n",
      "\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9049A80>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90496C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A9048E00>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 2247, in _stack_arrays\n",
      "    placement, arrays = zip(*tuples)\n",
      "                        ^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A904BEC0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 1001, in fast_xs\n",
      "    for i, rl in enumerate(blk.mgr_locs):\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n",
      "Exception ignored in: <generator object Person.working at 0x000001C9A90491C0>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 1001, in fast_xs\n",
      "    for i, rl in enumerate(blk.mgr_locs):\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: generator ignored GeneratorExit\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.4481387671270525\n",
      "0.2850652057512765\n",
      "0.26679602712167105\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>break_duration</th>\n",
       "      <th>break_timestamp</th>\n",
       "      <th>interruptions</th>\n",
       "      <th>completed_tasks</th>\n",
       "      <th>breaks</th>\n",
       "      <th>working_time</th>\n",
       "      <th>break_time</th>\n",
       "      <th>interruption_time</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>35</td>\n",
       "      <td>6</td>\n",
       "      <td>9</td>\n",
       "      <td>12.772163</td>\n",
       "      <td>53.629325</td>\n",
       "      <td>133.636971</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>41</td>\n",
       "      <td>16</td>\n",
       "      <td>11</td>\n",
       "      <td>155.162651</td>\n",
       "      <td>28.793252</td>\n",
       "      <td>120.187672</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>40</td>\n",
       "      <td>9</td>\n",
       "      <td>16</td>\n",
       "      <td>33.662940</td>\n",
       "      <td>69.491835</td>\n",
       "      <td>94.120830</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>40</td>\n",
       "      <td>16</td>\n",
       "      <td>6</td>\n",
       "      <td>92.483778</td>\n",
       "      <td>25.308718</td>\n",
       "      <td>115.668954</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>41</td>\n",
       "      <td>8</td>\n",
       "      <td>9</td>\n",
       "      <td>32.032936</td>\n",
       "      <td>28.432869</td>\n",
       "      <td>107.861319</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   break_duration  break_timestamp  interruptions  completed_tasks  breaks  \\\n",
       "0               0                0             35                6       9   \n",
       "0               0                0             41               16      11   \n",
       "0               0                0             40                9      16   \n",
       "0               0                0             40               16       6   \n",
       "0               0                0             41                8       9   \n",
       "\n",
       "   working_time  break_time  interruption_time  \n",
       "0     12.772163   53.629325         133.636971  \n",
       "0    155.162651   28.793252         120.187672  \n",
       "0     33.662940   69.491835          94.120830  \n",
       "0     92.483778   25.308718         115.668954  \n",
       "0     32.032936   28.432869         107.861319  "
      ]
     },
     "execution_count": 75,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "df_rand= simulate(30, 480, likelihood=True)\n",
    "\n",
    "aux = df_rand[['interruption_time','working_time','break_time','interruptions','breaks','completed_tasks']].apply(sum , axis=0)\n",
    "total = (aux['interruption_time']/aux['interruptions']) + aux['working_time']/aux['completed_tasks'] + aux['break_time']/aux['breaks']\n",
    "print(aux['working_time']/aux['completed_tasks']/total)\n",
    "print(aux['break_time']/aux['breaks']/total)\n",
    "print(aux['interruption_time']/aux['interruptions']/total)\n",
    "df_rand.head()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
